---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  ports:
  - name: http-port
    port: 80
    targetPort: 8888
  selector:
    notebook-name: jupyter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    notebook-name: jupyter
spec:
  selector:
    matchLabels:
      notebook-name: jupyter
  replicas: 1
  template:
    metadata:
      annotations:
        data.statcan.gc.ca/inject-blob-volumes: "true"
      labels:
        notebook-name: jupyter
    spec:
      volumes:
      - name: mc-download
        emptyDir: {}
      - name: mc-files
        emptyDir: {}
      initContainers:
      - name: mc
        image: minio/mc
        command: ["sh"]
        args:
        - -c
        - |
            cp /usr/bin/mc /home/jovyan/bin/
            mc -C /home/jovyan/.mc config host add s3proxy \
                http://s3proxy local-identity local-credential
            mc -C /home/jovyan/.mc config host add s3proxy-prob \
                http://s3proxy-prob local-identity local-credential
            chown -R 1000:1000 /home/jovyan/bin/ /home/jovyan/.mc
        volumeMounts:
        - name: mc-download
          mountPath: /home/jovyan/bin
        - name: mc-files
          mountPath: /home/jovyan/.mc
      containers:
      - name: jupyter
        args:
        - notebook
        - --ip=0.0.0.0
        - --no-browser
        - --port=8888
        - --NotebookApp.token=''
        - --NotebookApp.password=''
        - --NotebookApp.allow_origin='*'
        - --NotebookApp.authenticate_prometheus=False
        - --NotebookApp.default_url=/tree
        command:
        - jupyter
        image: jupyter/minimal-notebook
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: mc-download
          mountPath: /home/jovyan/bin
        - name: mc-files
          mountPath: /home/jovyan/.mc
