apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: bob-standard
