apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
  labels:
    app: seaweedfs
spec:
  selector:
    matchLabels:
      app: seaweedfs
  template:
    metadata:
      labels:
        app: seaweedfs
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: standard
      #initContainers:
      #  - name: seaweedfs-cache
      #    image: seaweedfs/seaweedfs
      #    command: ["sh"]
      #    args:
      #    - -c
      #    - |
      #        mkdir -p /data/standard/.seaweedfs.sys
      #        ln -s /data/standard/.seaweedfs.sys /data/.seaweedfs.sys
      #    volumeMounts:
      #    - name: data
      #      mountPath: /data/
      containers:
        - name: main
          image: docker.io/chrislusf/seaweedfs:2.97
          args:
          - server
          - -dir=/data/standard/
          - -s3
          volumeMounts:
          - name: data
            mountPath: /data/standard
          ports:
            - name: http
              containerPort: 80
