apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alice

resources:
- ns.yaml
- ../../test-deployments
# - ../../s3proxy/unclassified
- ../../s3proxy/fancy
- ../../s3proxy/protected-b
