apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../../apps/blob-csi-injector/deploy/manifest.yaml

# For local dev
patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: blob-csi-injector
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent

# For local dev
images:
- name: k8scc01covidacr.azurecr.io/blob-csi-injector
  newName: blob-csi-injector
  newTag: latest
