apiVersion: v1
kind: Service
metadata:
  name: s3proxy-prob
  labels:
    app: s3proxy-prob
    data.statcan.gc.ca/classification: "protected-b"
spec:
  selector:
    app: s3proxy-prob
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
