apiVersion: v1
kind: ConfigMap
metadata:
  name: s3proxy-config-prob
  labels:
    app: s3proxy-prob
    data.statcan.gc.ca/classification: "protected-b"
data:
  #S3PROXY_AUTHORIZATION: "none"
  S3PROXY_ENDPOINT: "http://0.0.0.0:80"
  S3PROXY_IGNORE_UNKNOWN_HEADERS: "true"
  JCLOUDS_PROVIDER: filesystem
  JCLOUDS_FILESYSTEM_BASEDIR: /home/jovyan/buckets/
