apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: standard
      initContainers:
        - name: minio-cache
          image: minio/minio
          command: ["sh"]
          args:
          - -c
          - |
              mkdir -p /data/standard/.minio.sys
              ln -s /data/standard/.minio.sys /data/.minio.sys
          volumeMounts:
          - name: data
            mountPath: /data/
      containers:
        - name: main
          image: minio/minio
          env:
            - name: MINIO_ACCESS_KEY
              value: admin
            - name: MINIO_SECRET_KEY
              value: password
          volumeMounts:
          - name: data
            mountPath: /data/standard
          ports:
            - containerPort: 9000
          command: [minio, gateway, nas, /data]
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
