apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: premium
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: alice-premium
