apiVersion: v1
kind: Service
metadata:
  name: s3proxy
  labels:
    app: s3proxy
spec:
  selector:
    app: s3proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: s3proxy-web
  labels:
    app: s3proxy-web
spec:
  type: LoadBalancer
  selector:
    app: s3proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
