apiVersion: v1
kind: ConfigMap
metadata:
  name: s3proxy-nginx-conf
data:
  nginx.conf: |
    worker_processes  3;
    pid /tmp/nginx.pid; # Changed from /var/run/nginx.pid
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  1024;
    }
    http {
      client_max_body_size 1G;
      server {
          listen       8080;
          server_name  _;
          sendfile on;

          location ~ ^/(index.html|explorer.css|explorer.js)$ {
              include  /etc/nginx/mime.types;
              root   html;
              index  index.html index.htm;
          }

          location ~ ^/s3/(index.html|explorer.css|explorer.js)$ {
              include  /etc/nginx/mime.types;
              root   html;
              index  index.html index.htm;
          }

          location /s3/ {
             rewrite /s3/(.*) /$1 break;

             proxy_http_version     1.1;
             proxy_redirect off;
             proxy_set_header       Connection "";
             proxy_set_header       Authorization '';
             proxy_set_header       Host "0.0.0.0:9000";
             proxy_set_header       X-Real-IP $remote_addr;
             proxy_set_header       X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_hide_header      x-amz-id-2;
             proxy_hide_header      x-amz-request-id;
             proxy_hide_header      x-amz-meta-server-side-encryption;
             proxy_hide_header      x-amz-server-side-encryption;
             proxy_hide_header      Set-Cookie;
             proxy_ignore_headers   Set-Cookie;
             proxy_intercept_errors on;
             add_header             Cache-Control max-age=31536000;

             proxy_pass http://0.0.0.0:9000;
          }
      }
    }
